# Generated by Django 2.2 on 2021-03-26 07:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20180425_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='seats',
            field=models.CharField(default='a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
